name: Validate

on:
  pull_request:
    branches: [main, dev, beta]

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hacs/action@main
        with:
          category: integration
          ignore: brands

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: home-assistant/actions/hassfest@master

  syntax:
    name: Python Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Check syntax
        run: find custom_components -name "*.py" -exec python -m py_compile {} +
